import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

<<<<<<< HEAD
import { ClerkLoaded, ClerkProvider } from "@clerk/nextjs";
=======
>>>>>>> origin/main
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Marketing Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#13131a] text-white`}
      >
        <ClerkProvider>
          <ClerkLoaded>{children}</ClerkLoaded>
        </ClerkProvider>
=======
      <body className={`${geistSans.variable} ${geistMono.variable} bg-[#13131a] text-white`}>
        {children}
>>>>>>> origin/main
      </body>
    </html>
  );
}
